spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://my-auth-server.com
          jwk-set-uri: https://my-auth-server.com/.well-known/jwks.json
  application:
    name: security-server
